services:
  datejar-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datejar-backend
    ports:
      - "8000:8000"
    depends_on:
      - datejar-db

  datejar-db:
    image: postgres:17
    container_name: datejar-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datejar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on:
      - datejar-backend

volumes:
  postgres_data: